server:
  port: 8081
kafka:
  bootstrap-servers: http://localhost:9092
  topic-name: kafka-spring-topic
  topic-json-name: kafka-spring-json-topic
  consumer:
    group-id: kafka-spring-group
    concurrency: 5

spring:
  kafka:
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false