zoo2:
  image: zookeeper:3.4.9
  ports:
    - "2183:2181"
  environment:
    ZOO_MY_ID: 1
    ZOO_PORT: 2181
    ZOO_SERVERS: server.1=zoo2:2888:3888
  volumes:
    - ./zoo2/data:/data
    - ./zoo2/datalog:/datalog

kafka2:
  image: confluentinc/cp-kafka:5.2.1
  ports:
    - "9096:9096"
    - "9097:9097"
  environment:
    KAFKA_ADVERTISED_LISTENERS: KAFKA_INTERNAL_LISTENER://localhost:9096, KAFKA_LOCAL_LISTENER://localhost:9097
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: KAFKA_INTERNAL_LISTENER:PLAINTEXT, KAFKA_LOCAL_LISTENER:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: KAFKA_INTERNAL_LISTENER
    KAFKA_ZOOKEEPER_CONNECT: "zoo2:2181"
    KAFKA_BROKER_ID: 1
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  volumes:
    - ./kafka2/data:/var/lib/kafka/data
  links:
    - zoo2:zoo2
