server:
  port: 8081

kafka:
  bootstrap-servers: http://localhost:9092
  topic-name: kafka-spring-topic
  topic-json-name: kafka-spring-json-topic
  consumer:
    group-id: kafka-spring-group
    concurrency: 5

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring:
          json:
            add:
              type:
                headers: false
  application:
    name: spring-kafka
  cloud:
    stream:
      default:
        producer:
          use-native-encoding: true
      bindings:
        cloud-stream-output:
          destination: kafka-spring-topic
      binding-retry-interval: 30
      kafka:
        binder:
          health-timeout: 20


management:
  health:
    binders:
      enabled: true
  endpoint:
    health:
      show-details: always